-- Criticality, as confirmed by Rodeo Express (spec open item 4).
--
-- GENERATED by bin/gen-position-seed.php --criticals from the Critical
-- column of docs/spec-v2.md section 8.3. Do not hand-edit.
--
-- 39 of 98 positions are critical: 23 in Unload, 37 in Bump and Run.
--
-- Migration 002 seeded 23, drawn from the proposed set in the spec. The
-- confirmed set is larger and differently shaped: one Starter, one
-- Computer, one Counter and one Runner per lane or stop, rather than just
-- the Starter and Computer. Two General Starters came off the list, because
-- an adjacent worker covers Woodlands and Special Events when people are
-- short, and Reed Road now carries one Computer and one Counter for the
-- group rather than one per gate.
--
-- 37 critical positions against a shift that can run 25 people is not an
-- error. It is the floor: at 37 everything runs, barely, and everyone gets
-- home. The board is expected to show red on a short night.
--
-- Data only, so this one really is atomic:
-- resm:atomic

-- Criticality does not vary by phase (spec 8.1), so both phase rows of a
-- position always agree and neither statement below names a phase.
UPDATE position_phase SET is_critical = 0;

UPDATE position_phase pp
    JOIN position p       ON p.id = pp.position_id
    JOIN position_group g ON g.id = p.group_id
SET pp.is_critical = 1
WHERE (g.code, p.label) IN (
    ('general', 'Main Committee Gate Lead'),
    ('general', 'Tent Entrance/Overheads Lead'),
    ('general', 'Bus Caller 1'),
    ('general', 'Curve 1'),
    ('naomi_crosswalk', 'Center Starter'),
    ('naomi_crosswalk', 'Naomi Crosswalk Perimeter 1'),
    ('naomi_crosswalk', 'Naomi Crosswalk Perimeter 2'),
    ('naomi_crosswalk', 'Naomi Crosswalk Perimeter 3'),
    ('naomi_crosswalk', 'Naomi Crosswalk Perimeter 4'),
    ('holly_hall_crosswalk', 'Holly Hall Center'),
    ('holly_hall_crosswalk', 'Holly Hall 1'),
    ('holly_hall_crosswalk', 'Holly Hall 2'),
    ('holly_hall_crosswalk', 'Holly Hall 3'),
    ('reed_road', 'Reed Starter 1'),
    ('reed_road', 'Reed Computer'),
    ('reed_road', 'Reed Counter 1'),
    ('reed_road', 'Reed/Employee Runner 1'),
    ('gold_badge_lt', 'GB/LT Starter 1'),
    ('gold_badge_lt', 'GB/LT Computer'),
    ('gold_badge_lt', 'GB/LT Counter 1'),
    ('gold_badge_lt', 'GB/LT Runner 1'),
    ('unload', 'Unload Starter'),
    ('unload', 'Unload Computer'),
    ('ost', 'OST Starter 1'),
    ('ost', 'OST Computer'),
    ('ost', 'OST Counter 1'),
    ('ost', 'OST Runner 1'),
    ('west_loop', 'WL Starter 1'),
    ('west_loop', 'WL Computer'),
    ('west_loop', 'WL Counter 1'),
    ('west_loop', 'WL Runner 1'),
    ('monroe', 'Monroe Starter 1'),
    ('monroe', 'Monroe Computer'),
    ('monroe', 'Monroe Counter 1'),
    ('monroe', 'Monroe Runner 1'),
    ('maxey', 'Maxey Starter'),
    ('maxey', 'Maxey Computer'),
    ('maxey', 'Maxey Counter 1'),
    ('maxey', 'Maxey Runner 1')
);

