-- Skills: ten of them, in two kinds, and what each position calls for.
--
-- GENERATED by bin/gen-position-seed.php --skills from docs/spec-v2.md
-- section 7. Do not hand-edit.
--
-- 10 skills. 80 of 98 positions map to one; the rest are their own jobs
-- with nothing shared to certify (7.2).
--
-- Nothing here restricts an assignment. Certification is not a permission and
-- preference is not a claim: both are shown beside a name so the officer can
-- decide, and who stands where is settled on the ground (7.4).
--
-- resm:atomic

-- Position skills go on the assign board chip row; equipment certifications
-- are roster information and stay off it (7.1).
ALTER TABLE skill ADD COLUMN kind ENUM('position','equipment') NOT NULL DEFAULT 'position' AFTER label;

-- The two new position skills (7.1).
INSERT INTO skill (id, code, label, kind, sort_order) VALUES (9, 'crosswalk_perimeter', 'Crosswalk Perimeter', 'position', 7);
INSERT INTO skill (id, code, label, kind, sort_order) VALUES (10, 'gate', 'Gate', 'position', 8);

-- Everything already seeded gets its kind, and the two equipment
-- certifications move to the end of the chip order without changing id.
UPDATE skill SET kind = 'position', sort_order = 1 WHERE code = 'radio';
UPDATE skill SET kind = 'position', sort_order = 2 WHERE code = 'starter';
UPDATE skill SET kind = 'position', sort_order = 3 WHERE code = 'computer';
UPDATE skill SET kind = 'position', sort_order = 4 WHERE code = 'counter';
UPDATE skill SET kind = 'position', sort_order = 5 WHERE code = 'runner';
UPDATE skill SET kind = 'position', sort_order = 6 WHERE code = 'crosswalk_middle';
UPDATE skill SET kind = 'equipment', sort_order = 9 WHERE code = 'forklift';
UPDATE skill SET kind = 'equipment', sort_order = 10 WHERE code = 'golfcart';

-- At most one job skill per position. Radio stays its own flag because it is
-- orthogonal: Reed Starter 1 wants a Starter AND a radio.
ALTER TABLE position ADD COLUMN skill_id TINYINT UNSIGNED NULL AFTER is_radio,
    ADD CONSTRAINT fk_position_skill FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE SET NULL;

-- gate: 12 positions
UPDATE position SET skill_id = 10 WHERE id IN (1, 2, 48, 49, 50, 72, 73, 81, 82, 90, 91, 98);
-- starter: 14 positions
UPDATE position SET skill_id = 2 WHERE id IN (13, 15, 36, 37, 51, 52, 60, 63, 64, 74, 75, 83, 84, 92);
-- runner: 19 positions
UPDATE position SET skill_id = 5 WHERE id IN (14, 16, 44, 45, 46, 47, 56, 57, 58, 68, 69, 70, 71, 79, 80, 88, 89, 96, 97);
-- crosswalk_middle: 2 positions
UPDATE position SET skill_id = 6 WHERE id IN (17, 30);
-- crosswalk_perimeter: 11 positions
UPDATE position SET skill_id = 9 WHERE id IN (18, 19, 20, 21, 22, 23, 31, 32, 33, 34, 35);
-- computer: 8 positions
UPDATE position SET skill_id = 3 WHERE id IN (38, 39, 53, 61, 65, 76, 85, 93);
-- counter: 14 positions
UPDATE position SET skill_id = 4 WHERE id IN (40, 41, 42, 43, 54, 55, 66, 67, 77, 78, 86, 87, 94, 95);

-- Certified and preferred are independent facts about the same pair (7.3).
-- A man can be certified in something he would rather not do, and prefer
-- something he is not yet certified for -- which is a training list nobody
-- had to compile. Certified is granted_at being set, so it becomes nullable.
ALTER TABLE user_skill
    MODIFY COLUMN granted_at DATETIME NULL DEFAULT NULL,
    ADD COLUMN is_preferred TINYINT(1) NOT NULL DEFAULT 0 AFTER skill_id,
    ADD COLUMN preferred_at DATETIME NULL DEFAULT NULL AFTER is_preferred;

