-- 008 — the tarmac map lands, and the first position definitions with it.
--
-- Two of the deliverables Rodeo Express owed (spec 11.3, 11.4) arrived in
-- August 2026: a description of the ground detailed enough to draw, and the
-- 2026 Committee Handbook to scrape position write-ups from.
--
-- map_ref: every one of the 98 positions gets the id of its marker in
-- public/assets/map/tarmac.svg. Both sides are generated by
-- bin/gen-tarmac-map.php from one naming rule, and its --check mode holds
-- this file and the SVG to the generator. When the committee corrects a
-- placement, the marker moves in the SVG; the ids — and these rows — do not
-- change.
--
-- definition: the "What's this?" text (spec 6.5), written per family as
-- 11.3 asks. Only what the handbook and the committee's description actually
-- support is written; the rest stays NULL and the UI keeps saying the
-- write-up is still owed, which is the truth. Nothing here is invented.
--
-- Pure data, so it opts into a transaction:
-- resm:atomic

-- ---------------------------------------------------------------------------
-- map_ref, one row per position (generated: bin/gen-tarmac-map.php --refs)
-- ---------------------------------------------------------------------------

UPDATE position SET map_ref = 'pos-main-committee-gate-lead' WHERE label = 'Main Committee Gate Lead';
UPDATE position SET map_ref = 'pos-main-committee-gate-2' WHERE label = 'Main Committee Gate 2';
UPDATE position SET map_ref = 'pos-tent-entrance-overheads-lead' WHERE label = 'Tent Entrance/Overheads Lead';
UPDATE position SET map_ref = 'pos-tent-entrance-overheads-2' WHERE label = 'Tent Entrance/Overheads 2';
UPDATE position SET map_ref = 'pos-tent-entrance-overheads-3' WHERE label = 'Tent Entrance/Overheads 3';
UPDATE position SET map_ref = 'pos-tent-entrance-overheads-4' WHERE label = 'Tent Entrance/Overheads 4';
UPDATE position SET map_ref = 'pos-tent-entrance-overheads-5' WHERE label = 'Tent Entrance/Overheads 5';
UPDATE position SET map_ref = 'pos-tent-entrance-overheads-6' WHERE label = 'Tent Entrance/Overheads 6';
UPDATE position SET map_ref = 'pos-bus-caller-1' WHERE label = 'Bus Caller 1';
UPDATE position SET map_ref = 'pos-bus-caller-2' WHERE label = 'Bus Caller 2';
UPDATE position SET map_ref = 'pos-curve-1' WHERE label = 'Curve 1';
UPDATE position SET map_ref = 'pos-curve-2' WHERE label = 'Curve 2';
UPDATE position SET map_ref = 'pos-woodlands-starter' WHERE label = 'Woodlands Starter';
UPDATE position SET map_ref = 'pos-woodlands-runner' WHERE label = 'Woodlands Runner';
UPDATE position SET map_ref = 'pos-special-events-starter' WHERE label = 'Special Events Starter';
UPDATE position SET map_ref = 'pos-special-events-runner' WHERE label = 'Special Events Runner';
UPDATE position SET map_ref = 'pos-center-starter' WHERE label = 'Center Starter';
UPDATE position SET map_ref = 'pos-naomi-crosswalk-perimeter-1' WHERE label = 'Naomi Crosswalk Perimeter 1';
UPDATE position SET map_ref = 'pos-naomi-crosswalk-perimeter-2' WHERE label = 'Naomi Crosswalk Perimeter 2';
UPDATE position SET map_ref = 'pos-naomi-crosswalk-perimeter-3' WHERE label = 'Naomi Crosswalk Perimeter 3';
UPDATE position SET map_ref = 'pos-naomi-crosswalk-perimeter-4' WHERE label = 'Naomi Crosswalk Perimeter 4';
UPDATE position SET map_ref = 'pos-naomi-crosswalk-perimeter-5' WHERE label = 'Naomi Crosswalk Perimeter 5';
UPDATE position SET map_ref = 'pos-naomi-crosswalk-perimeter-6' WHERE label = 'Naomi Crosswalk Perimeter 6';
UPDATE position SET map_ref = 'pos-naomi-bridge-1' WHERE label = 'Naomi Bridge 1';
UPDATE position SET map_ref = 'pos-naomi-bridge-2' WHERE label = 'Naomi Bridge 2';
UPDATE position SET map_ref = 'pos-naomi-bridge-3' WHERE label = 'Naomi Bridge 3';
UPDATE position SET map_ref = 'pos-naomi-bridge-4' WHERE label = 'Naomi Bridge 4';
UPDATE position SET map_ref = 'pos-naomi-bridge-5' WHERE label = 'Naomi Bridge 5';
UPDATE position SET map_ref = 'pos-naomi-bridge-6' WHERE label = 'Naomi Bridge 6';
UPDATE position SET map_ref = 'pos-holly-hall-center' WHERE label = 'Holly Hall Center';
UPDATE position SET map_ref = 'pos-holly-hall-1' WHERE label = 'Holly Hall 1';
UPDATE position SET map_ref = 'pos-holly-hall-2' WHERE label = 'Holly Hall 2';
UPDATE position SET map_ref = 'pos-holly-hall-3' WHERE label = 'Holly Hall 3';
UPDATE position SET map_ref = 'pos-holly-hall-4' WHERE label = 'Holly Hall 4';
UPDATE position SET map_ref = 'pos-holly-hall-5' WHERE label = 'Holly Hall 5';
UPDATE position SET map_ref = 'pos-reed-starter-1' WHERE label = 'Reed Starter 1';
UPDATE position SET map_ref = 'pos-reed-starter-2' WHERE label = 'Reed Starter 2';
UPDATE position SET map_ref = 'pos-reed-computer' WHERE label = 'Reed Computer';
UPDATE position SET map_ref = 'pos-employee-computer' WHERE label = 'Employee Computer';
UPDATE position SET map_ref = 'pos-reed-counter-1' WHERE label = 'Reed Counter 1';
UPDATE position SET map_ref = 'pos-reed-counter-2' WHERE label = 'Reed Counter 2';
UPDATE position SET map_ref = 'pos-employee-counter-1' WHERE label = 'Employee Counter 1';
UPDATE position SET map_ref = 'pos-employee-counter-2' WHERE label = 'Employee Counter 2';
UPDATE position SET map_ref = 'pos-reed-employee-runner-1' WHERE label = 'Reed/Employee Runner 1';
UPDATE position SET map_ref = 'pos-reed-employee-runner-2' WHERE label = 'Reed/Employee Runner 2';
UPDATE position SET map_ref = 'pos-reed-employee-runner-3' WHERE label = 'Reed/Employee Runner 3';
UPDATE position SET map_ref = 'pos-reed-employee-runner-4' WHERE label = 'Reed/Employee Runner 4';
UPDATE position SET map_ref = 'pos-reed-employee-back-gate-1' WHERE label = 'Reed/Employee Back Gate 1';
UPDATE position SET map_ref = 'pos-reed-employee-back-gate-2' WHERE label = 'Reed/Employee Back Gate 2';
UPDATE position SET map_ref = 'pos-reed-employee-back-gate-3' WHERE label = 'Reed/Employee Back Gate 3';
UPDATE position SET map_ref = 'pos-gb-lt-starter-1' WHERE label = 'GB/LT Starter 1';
UPDATE position SET map_ref = 'pos-gb-lt-starter-2' WHERE label = 'GB/LT Starter 2';
UPDATE position SET map_ref = 'pos-gb-lt-computer' WHERE label = 'GB/LT Computer';
UPDATE position SET map_ref = 'pos-gb-lt-counter-1' WHERE label = 'GB/LT Counter 1';
UPDATE position SET map_ref = 'pos-gb-lt-counter-2' WHERE label = 'GB/LT Counter 2';
UPDATE position SET map_ref = 'pos-gb-lt-runner-1' WHERE label = 'GB/LT Runner 1';
UPDATE position SET map_ref = 'pos-gb-lt-runner-2' WHERE label = 'GB/LT Runner 2';
UPDATE position SET map_ref = 'pos-gb-lt-runner-3' WHERE label = 'GB/LT Runner 3';
UPDATE position SET map_ref = 'pos-gb-lt-back-of-tent' WHERE label = 'GB/LT Back of Tent';
UPDATE position SET map_ref = 'pos-unload-starter' WHERE label = 'Unload Starter';
UPDATE position SET map_ref = 'pos-unload-computer' WHERE label = 'Unload Computer';
UPDATE position SET map_ref = 'pos-unload-helper-crowd-control' WHERE label = 'Unload Helper/Crowd Control';
UPDATE position SET map_ref = 'pos-ost-starter-1' WHERE label = 'OST Starter 1';
UPDATE position SET map_ref = 'pos-ost-starter-2' WHERE label = 'OST Starter 2';
UPDATE position SET map_ref = 'pos-ost-computer' WHERE label = 'OST Computer';
UPDATE position SET map_ref = 'pos-ost-counter-1' WHERE label = 'OST Counter 1';
UPDATE position SET map_ref = 'pos-ost-counter-2' WHERE label = 'OST Counter 2';
UPDATE position SET map_ref = 'pos-ost-runner-1' WHERE label = 'OST Runner 1';
UPDATE position SET map_ref = 'pos-ost-runner-2' WHERE label = 'OST Runner 2';
UPDATE position SET map_ref = 'pos-ost-runner-3' WHERE label = 'OST Runner 3';
UPDATE position SET map_ref = 'pos-ost-runner-4' WHERE label = 'OST Runner 4';
UPDATE position SET map_ref = 'pos-ost-back-gate-1' WHERE label = 'OST Back Gate 1';
UPDATE position SET map_ref = 'pos-ost-back-gate-2' WHERE label = 'OST Back Gate 2';
UPDATE position SET map_ref = 'pos-wl-starter-1' WHERE label = 'WL Starter 1';
UPDATE position SET map_ref = 'pos-wl-starter-2' WHERE label = 'WL Starter 2';
UPDATE position SET map_ref = 'pos-wl-computer' WHERE label = 'WL Computer';
UPDATE position SET map_ref = 'pos-wl-counter-1' WHERE label = 'WL Counter 1';
UPDATE position SET map_ref = 'pos-wl-counter-2' WHERE label = 'WL Counter 2';
UPDATE position SET map_ref = 'pos-wl-runner-1' WHERE label = 'WL Runner 1';
UPDATE position SET map_ref = 'pos-wl-runner-2' WHERE label = 'WL Runner 2';
UPDATE position SET map_ref = 'pos-wl-back-gate-1' WHERE label = 'WL Back Gate 1';
UPDATE position SET map_ref = 'pos-wl-back-gate-2' WHERE label = 'WL Back Gate 2';
UPDATE position SET map_ref = 'pos-monroe-starter-1' WHERE label = 'Monroe Starter 1';
UPDATE position SET map_ref = 'pos-monroe-starter-2' WHERE label = 'Monroe Starter 2';
UPDATE position SET map_ref = 'pos-monroe-computer' WHERE label = 'Monroe Computer';
UPDATE position SET map_ref = 'pos-monroe-counter-1' WHERE label = 'Monroe Counter 1';
UPDATE position SET map_ref = 'pos-monroe-counter-2' WHERE label = 'Monroe Counter 2';
UPDATE position SET map_ref = 'pos-monroe-runner-1' WHERE label = 'Monroe Runner 1';
UPDATE position SET map_ref = 'pos-monroe-runner-2' WHERE label = 'Monroe Runner 2';
UPDATE position SET map_ref = 'pos-monroe-back-gate-1' WHERE label = 'Monroe Back Gate 1';
UPDATE position SET map_ref = 'pos-monroe-back-gate-2' WHERE label = 'Monroe Back Gate 2';
UPDATE position SET map_ref = 'pos-maxey-starter' WHERE label = 'Maxey Starter';
UPDATE position SET map_ref = 'pos-maxey-computer' WHERE label = 'Maxey Computer';
UPDATE position SET map_ref = 'pos-maxey-counter-1' WHERE label = 'Maxey Counter 1';
UPDATE position SET map_ref = 'pos-maxey-counter-2' WHERE label = 'Maxey Counter 2';
UPDATE position SET map_ref = 'pos-maxey-runner-1' WHERE label = 'Maxey Runner 1';
UPDATE position SET map_ref = 'pos-maxey-runner-2' WHERE label = 'Maxey Runner 2';
UPDATE position SET map_ref = 'pos-maxey-back-gate' WHERE label = 'Maxey Back Gate';

-- ---------------------------------------------------------------------------
-- Definitions, per family (spec 11.3), scraped from the 2026 Committee
-- Handbook and the committee's own description of the ground. 57 of 98;
-- the other 41 stay NULL until Rodeo Express writes them up, and the app
-- keeps saying so.
-- ---------------------------------------------------------------------------

-- Starters. The handbook: Rodeo Express took the Bus Starter positions over
-- from METRO in 2007; the red vest is the Bus Operations Starter vest and
-- carries a radio; never work in the street or stand in front of a moving
-- vehicle. The committee: starters stand in the bus lanes, even with their
-- stop.
UPDATE position SET definition = 'Dispatches buses for the Reed Road stop from the bus lanes on the west side of the tent, even with the stop - red vest and radio, a job Rodeo Express has staffed itself since taking it over from METRO in 2007. Never work in the street or stand in front of a moving bus.'
 WHERE label IN ('Reed Starter 1', 'Reed Starter 2');
UPDATE position SET definition = 'Dispatches buses for the OST/Smithlands stop from the bus lanes on the west side of the tent, even with the stop - red vest and radio, a job Rodeo Express has staffed itself since taking it over from METRO in 2007. Never work in the street or stand in front of a moving bus.'
 WHERE label IN ('OST Starter 1', 'OST Starter 2');
UPDATE position SET definition = 'Dispatches buses for the West Loop stop from the bus lanes on the west side of the tent, even with the stop - red vest and radio, a job Rodeo Express has staffed itself since taking it over from METRO in 2007. Never work in the street or stand in front of a moving bus.'
 WHERE label IN ('WL Starter 1', 'WL Starter 2');
UPDATE position SET definition = 'Dispatches buses for the Monroe stop from the bus lanes on the west side of the tent, even with the stop - red vest and radio, a job Rodeo Express has staffed itself since taking it over from METRO in 2007. Never work in the street or stand in front of a moving bus.'
 WHERE label IN ('Monroe Starter 1', 'Monroe Starter 2');
UPDATE position SET definition = 'Dispatches buses for the Maxey stop from the bus lanes on the west side of the tent, even with the stop - red vest and radio, a job Rodeo Express has staffed itself since taking it over from METRO in 2007. Never work in the street or stand in front of a moving bus.'
 WHERE label = 'Maxey Starter';
UPDATE position SET definition = 'Dispatches buses for The Woodlands Express stop from the bus lanes on the west side of the tent, even with the stop - red vest and radio. Never work in the street or stand in front of a moving bus.'
 WHERE label = 'Woodlands Starter';
UPDATE position SET definition = 'Dispatches buses for the Special Events stop from the bus lanes on the west side of the tent, even with the stop - red vest and radio. Never work in the street or stand in front of a moving bus.'
 WHERE label = 'Special Events Starter';
UPDATE position SET definition = 'Dispatches buses for the Gold Badge / LT stop - red vest and radio, a job Rodeo Express has staffed itself since taking it over from METRO in 2007. Never work in the street or stand in front of a moving bus.'
 WHERE label IN ('GB/LT Starter 1', 'GB/LT Starter 2');
UPDATE position SET definition = 'Dispatches buses through the lanes while arriving guests unload - the first phase of the night, shared by several committeemen at once. Red vest and radio, and never work in the street.'
 WHERE label = 'Unload Starter';

-- Computers and counters. The handbook: real-time passenger counts have
-- driven Rodeo Express bus operations since 1991, and counts are entered
-- into the committee computer system. The committee: computers, counters
-- and runners work just outside the west side of the tent.
UPDATE position SET definition = 'Enters the Reed Road boarding counts into the Rodeo Express computer system, working just outside the west side of the tent. Real-time passenger counts have driven bus operations since 1991.'
 WHERE label = 'Reed Computer';
UPDATE position SET definition = 'Enters boarding counts for the employee buses at the Reed Road employee gates, working just outside the west side of the tent. NRG, Aramark, Aramco and carnival employees ride with their credentials.'
 WHERE label = 'Employee Computer';
UPDATE position SET definition = 'Enters the Gold Badge / LT boarding counts into the Rodeo Express computer system. Real-time passenger counts have driven bus operations since 1991.'
 WHERE label = 'GB/LT Computer';
UPDATE position SET definition = 'Enters the OST/Smithlands boarding counts into the Rodeo Express computer system, working just outside the west side of the tent. Real-time passenger counts have driven bus operations since 1991.'
 WHERE label = 'OST Computer';
UPDATE position SET definition = 'Enters the West Loop boarding counts into the Rodeo Express computer system, working just outside the west side of the tent. Real-time passenger counts have driven bus operations since 1991.'
 WHERE label = 'WL Computer';
UPDATE position SET definition = 'Enters the Monroe boarding counts into the Rodeo Express computer system, working just outside the west side of the tent. Real-time passenger counts have driven bus operations since 1991.'
 WHERE label = 'Monroe Computer';
UPDATE position SET definition = 'Enters the Maxey boarding counts into the Rodeo Express computer system, working just outside the west side of the tent. Real-time passenger counts have driven bus operations since 1991.'
 WHERE label = 'Maxey Computer';
UPDATE position SET definition = 'Records counts as arriving buses unload - the first phase of the night, shared by more than one committeeman at once, working just outside the west side of the tent.'
 WHERE label = 'Unload Computer';

UPDATE position SET definition = 'Counts every passenger boarding at the Reed Road stop. The counts feed the computer and are the real-time ridership numbers Rodeo Express has used to refine bus operations since 1991.'
 WHERE label IN ('Reed Counter 1', 'Reed Counter 2');
UPDATE position SET definition = 'Counts passengers boarding the employee buses at the Reed Road employee gates. The counts feed the computer and the daily ridership numbers.'
 WHERE label IN ('Employee Counter 1', 'Employee Counter 2');
UPDATE position SET definition = 'Counts every passenger boarding at the Gold Badge / LT stop. The counts feed the computer and are the real-time ridership numbers Rodeo Express has used to refine bus operations since 1991.'
 WHERE label IN ('GB/LT Counter 1', 'GB/LT Counter 2');
UPDATE position SET definition = 'Counts every passenger boarding at the OST/Smithlands stop. The counts feed the computer and are the real-time ridership numbers Rodeo Express has used to refine bus operations since 1991.'
 WHERE label IN ('OST Counter 1', 'OST Counter 2');
UPDATE position SET definition = 'Counts every passenger boarding at the West Loop stop. The counts feed the computer and are the real-time ridership numbers Rodeo Express has used to refine bus operations since 1991.'
 WHERE label IN ('WL Counter 1', 'WL Counter 2');
UPDATE position SET definition = 'Counts every passenger boarding at the Monroe stop. The counts feed the computer and are the real-time ridership numbers Rodeo Express has used to refine bus operations since 1991.'
 WHERE label IN ('Monroe Counter 1', 'Monroe Counter 2');
UPDATE position SET definition = 'Counts every passenger boarding at the Maxey stop. The counts feed the computer and are the real-time ridership numbers Rodeo Express has used to refine bus operations since 1991.'
 WHERE label IN ('Maxey Counter 1', 'Maxey Counter 2');

-- The crosswalks and the bridge. The handbook: the walkover bridge went in
-- at Naomi in 2017 to handle patrons walking in from the east side and to
-- improve the movement of buses; flashlights must be used when assisting
-- pedestrians across crosswalks; never stand in front of moving vehicles.
UPDATE position SET definition = 'Directs buses and patrons from the center of the Naomi crosswalk, northwest of the tent - radio required. Use a flashlight when assisting pedestrians across, and never stand in front of moving vehicles.'
 WHERE label = 'Center Starter';
UPDATE position SET definition = 'Perimeter position on the Naomi crosswalk, northwest of the tent, guiding patrons safely across. Flashlights must be used when assisting pedestrians across a crosswalk; safety vest at all times.'
 WHERE label IN ('Naomi Crosswalk Perimeter 1', 'Naomi Crosswalk Perimeter 2',
                 'Naomi Crosswalk Perimeter 3', 'Naomi Crosswalk Perimeter 4',
                 'Naomi Crosswalk Perimeter 5', 'Naomi Crosswalk Perimeter 6');
UPDATE position SET definition = 'Works the walkover bridge at Naomi, northwest of the tent - installed in 2017 to carry patrons walking in from the east side while the buses keep moving beneath it.'
 WHERE label IN ('Naomi Bridge 1', 'Naomi Bridge 2', 'Naomi Bridge 3',
                 'Naomi Bridge 4', 'Naomi Bridge 5', 'Naomi Bridge 6');
UPDATE position SET definition = 'Directs buses and patrons from the center of the Holly Hall crosswalk, southwest of the tent - radio required. Use a flashlight when assisting pedestrians across, and never stand in front of moving vehicles.'
 WHERE label = 'Holly Hall Center';
UPDATE position SET definition = 'Works the Holly Hall crosswalk, southwest of the tent, guiding patrons safely across. Flashlights must be used when assisting pedestrians across a crosswalk; safety vest at all times.'
 WHERE label IN ('Holly Hall 1', 'Holly Hall 2', 'Holly Hall 3',
                 'Holly Hall 4', 'Holly Hall 5');

-- The committee gate. The committee: it sits on the north side of the Bus
-- Ops office complex. The handbook: everyone signs in on arrival and signs
-- out before leaving.
UPDATE position SET definition = 'Works the committee gate on the north side of the Bus Ops office complex - the gate committeemen use to reach the tarmac. Everyone signs in with team leadership on arrival and signs out before leaving.'
 WHERE label IN ('Main Committee Gate Lead', 'Main Committee Gate 2');

-- ---------------------------------------------------------------------------
-- The assign board shows definitions, so boards still live when this lands
-- need to hear about it — same rule as every Matrix Editor write (spec 10.2).
-- ---------------------------------------------------------------------------

UPDATE state_version sv
  JOIN shift sh ON sh.id = sv.shift_id
   SET sv.version = sv.version + 1
 WHERE sh.ends_at > UTC_TIMESTAMP();
