<?php

declare(strict_types=1);

use Resm\App;
use Resm\TarmacMap;

/**
 * The tarmac map viewer (spec 6.5, 11.4) — and, since Phase 7, the drawing
 * itself.
 *
 * Rodeo Express supplied the layout in August 2026 and the drawing is now
 * generated by bin/gen-tarmac-map.php and shipped. What holds it together is
 * the id contract: every one of the 98 positions carries a map_ref
 * (migration 008), and every map_ref is exactly one element id in the SVG.
 * These tests pin that contract from both sides, because a ref without a
 * marker is a man whose highlight silently never appears.
 */

function mapApp(): App
{
    return App::boot(dirname(__DIR__));
}

/**
 * Swap a stand-in drawing in for the real one, run $work, and put the real
 * one back. The refusal rules in TarmacMap::read are about files, so they
 * need files to prove them — but never at the price of the shipped drawing.
 */
function withDrawing(string $svg, callable $work): void
{
    $app = mapApp();
    $file = TarmacMap::path($app);
    $real = is_file($file) ? (string) file_get_contents($file) : null;

    if (!is_dir(dirname($file))) {
        mkdir(dirname($file), 0755, true);
    }

    file_put_contents($file, $svg);

    try {
        $work($app);
    } finally {
        if ($real === null) {
            unlink($file);
        } else {
            file_put_contents($file, $real);
        }
    }
}

// ---------------------------------------------------------------------------
// The shipped drawing
// ---------------------------------------------------------------------------

test('the tarmac drawing is shipped and the viewer picks it up', function (): void {
    $app = mapApp();

    assertTrue(TarmacMap::isAvailable($app));

    $svg = (string) TarmacMap::read($app);
    assertTrue(str_contains($svg, '<svg'), 'it must be a drawing');
    assertTrue(str_contains($svg, 'id="pos-reed-starter-1"'), 'positions must be addressable');
});

test('the drawing carries no script and no styling of its own', function (): void {
    $app = mapApp();
    $svg = (string) file_get_contents(TarmacMap::path($app));

    // TarmacMap::read would refuse script — this asserts the file we SHIP
    // never trips that refusal, and stays within the page CSP.
    assertSame(false, stripos($svg, '<script'), 'no script elements');
    assertSame(false, stripos($svg, 'javascript:'), 'no script URLs');
    assertSame(false, stripos($svg, '<style'), 'style-src self blocks inline style elements');
    assertSame(false, stripos($svg, ' style='), 'and inline style attributes');
    assertSame(false, stripos($svg, 'href='), 'no links or external references');
});

test('every position map_ref is exactly one element id in the drawing, and no extras', function (): void {
    inRollback(function (Resm\Database $db): void {
        $svg = (string) file_get_contents(TarmacMap::path(mapApp()));

        $rows = $db->all('SELECT label, map_ref FROM position');
        assertCount(98, $rows);

        $refs = [];
        foreach ($rows as $row) {
            $ref = $row['map_ref'];
            assertTrue($ref !== null && $ref !== '', "{$row['label']} must carry a map_ref");
            assertSame($ref, TarmacMap::ref((string) $ref), "{$row['label']}: ref must be selector-safe");
            assertTrue(!isset($refs[$ref]), "map_ref {$ref} must be unique");
            $refs[(string) $ref] = true;

            $count = substr_count($svg, 'id="' . $ref . '"');
            assertSame(1, $count, "{$row['label']}: {$ref} must appear exactly once in the SVG");
        }

        // The other direction: an id in the drawing that no position claims is
        // a marker that can never light up — most likely a renamed position
        // whose SVG was not regenerated.
        preg_match_all('/id="(pos-[A-Za-z0-9_-]+)"/', $svg, $m);
        assertCount(98, $m[1]);
        foreach ($m[1] as $id) {
            assertTrue(isset($refs[$id]), "SVG marker {$id} belongs to no position");
        }
    });
});

// ---------------------------------------------------------------------------
// The definitions that arrived with it (spec 11.3)
// ---------------------------------------------------------------------------

test('definitions cover the families the handbook supports, and no more', function (): void {
    inRollback(function (Resm\Database $db): void {
        // 57 written, 41 honestly still owed. If Rodeo Express supplies more,
        // this number moves with the new migration that lands them.
        assertSame(57, (int) $db->value('SELECT COUNT(*) FROM position WHERE definition IS NOT NULL'));

        // Families that must be written: starters, computers, counters, the
        // crosswalks and bridge, the committee gate.
        foreach (['Reed Starter 1', 'OST Computer', 'Maxey Counter 2',
                  'Naomi Bridge 4', 'Holly Hall Center', 'Main Committee Gate Lead',
                  'Unload Starter'] as $label) {
            $text = (string) $db->value('SELECT definition FROM position WHERE label = :l', ['l' => $label]);
            assertTrue(strlen($text) > 60, "{$label} must carry a real write-up");
        }

        // Positions the handbook says nothing about stay NULL — the UI says
        // "still being written up", which is the truth. Writing filler here
        // would hide that the deliverable is still part-owed.
        foreach (['Reed/Employee Runner 1', 'OST Back Gate 1', 'Bus Caller 1',
                  'Curve 1', 'Tent Entrance/Overheads Lead', 'GB/LT Back of Tent'] as $label) {
            assertSame(
                null,
                $db->value('SELECT definition FROM position WHERE label = :l', ['l' => $label]),
                "{$label} has no handbook write-up and must stay owed"
            );
        }

        // Interchangeable positions share one definition (11.3: per family).
        $naomi = $db->all("SELECT DISTINCT definition FROM position WHERE label LIKE 'Naomi Bridge %'");
        assertCount(1, $naomi);
    });
});

// ---------------------------------------------------------------------------
// The refusal rules, proven against stand-in files
// ---------------------------------------------------------------------------

test('a file that is not a drawing is not rendered as one', function (): void {
    withDrawing('this is not an svg', function (App $app): void {
        assertSame(null, TarmacMap::read($app));
    });
});

test('a drawing carrying script is refused', function (): void {
    withDrawing(
        '<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script><rect id="R1"/></svg>',
        function (App $app): void {
            // The page's CSP is script-src 'self', so it would not run anyway.
            // But a site plan has no business carrying one, and refusing is a
            // clearer signal than quietly serving a file somebody has been at
            // (spec 10.5).
            assertSame(null, TarmacMap::read($app));
        }
    );
});

test('the placeholder still lists what is needed, for the day the file goes missing', function (): void {
    $needed = TarmacMap::needed();

    assertCount(4, $needed);
    assertTrue(str_contains($needed[1], '98 positions'), 'it must say how many positions');
});

test('the drawing is precached with the rest of the shell', function (): void {
    $assets = Resm\Pwa\Shell::assets(mapApp());
    $found = false;

    foreach ($assets as $url) {
        if (str_contains($url, 'map/tarmac.svg')) {
            $found = true;
        }
    }

    // Spec 10.3 caches the tarmac map cache-first: it is the screen most
    // likely to be wanted in the one place there is no signal.
    assertTrue($found, 'the drawing must join the precached shell');
});

// ---------------------------------------------------------------------------
// Addressing a position inside it
// ---------------------------------------------------------------------------

test('a map_ref is only used when it is safe to put in a selector', function (): void {
    // map_ref is data alongside the drawing. A stray space or quote in one
    // row must mean "no highlight on that position", never a broken query
    // that takes out the whole screen.
    assertSame('R1', TarmacMap::ref('R1'));
    assertSame('pos-reed-starter-1', TarmacMap::ref('pos-reed-starter-1'));
    assertSame('Naomi_Bridge_1', TarmacMap::ref('Naomi_Bridge_1'));

    assertSame(null, TarmacMap::ref(null), 'no ref set');
    assertSame(null, TarmacMap::ref(''), 'empty');
    assertSame(null, TarmacMap::ref('reed gate'), 'a space');
    assertSame(null, TarmacMap::ref('R1"], [x'), 'a selector escape');
    assertSame(null, TarmacMap::ref('1R'), 'ids do not start with a digit');
    assertSame(null, TarmacMap::ref(str_repeat('a', 61)), 'longer than the column');
});
